# Generated by Django 3.2.18 on 2023-06-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_appointment_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='day',
        ),
    ]
