# Generated by Django 3.2.18 on 2023-06-28 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_appointment_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='day',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
